### ISSUE TITLE
CTRL+O crashes

### ISSUE THREAD

**Issue by madgarden** [wjaguar/mtPaint#12]
When CTRL+O is pressed to display the file open dialog, mtpaint exits. Ubuntu 14.04.

**Comment by wjaguar** [comment]
Works for me (on Slackware) and for numerous Puppy Linux users.
Therefore, more details needed.
First, does opening the dialog _through the menu_ work, or not?

**Comment by madgarden** [comment]
Yes, that did work. Also when I went to File/Actions/Configure, that also
crashed/exited.

I then rolled back to 884c87a63bacbe5b8233a6e319e582a486709d0a because I
needed to get some work done.

And so now I just cloned the latest into a new location for testing... and
now can't reproduce. So, *BIG SHRUG*. Will keep an eye out for if it
happens again.

**Comment by wjaguar** [comment]
If you happen upon this problem again, see if the "Paste Text (FreeType)" doesn't similarly misbehave. Because the only thing similar between fileselector and "Actions/Configure", is the specific type of list widget which FreeType text tool does also share.

**Comment by madgarden** [comment]
Will do!

Paul
