### ISSUE TITLE
(Feature) Custom zoom rate? 

### ISSUE THREAD

**Issue by andreas--e** [wjaguar/mtPaint#13]
This program is great, especially for ex-Windows users who are used to MSPAINT look&feel. Very good work.
However, what I'm still missing is a way to hand-edit the percentage value in the zoom rate dropdown menu, inserting a custom value. Most gfx tools do allow this, but mtPaint still does not.
I often need a 1.5 factor in my zoom rates, i. e. 150 % but currently it will only skip from original size to twice the size.

**Comment by wjaguar** [comment]
Do not expect anything like this anytime soon. The entire rendering pipeline in mtPaint is literally built around the "integer multiplier or integer divisor" scheme; there is nothing _so_ nice in a custom zoom, as to warrant a rewrite of the whole renderer, or even a half of it.

**Comment by andreas--e** [comment]
OMG, I wasn't aware of that.
But why not leave it open to prevent users from missing it and re-requesting the same thing sometime?
