### ISSUE TITLE
Cursor highlight in palette for currently selected colour index

### ISSUE THREAD

**Issue by madgarden** [wjaguar/mtPaint#18]
It'd be super handy if there was a cursor or highlight around the currently selected palette index (in the full palette view), especially when using [ ] to navigate the palette, or when using the dropper to pick up a colour. When masking colours for replacement and such, picking a colour from the image and then trying to figure out which one it is in the palette is very tedious. A highlight on the selected colour would solve this.

**Comment by wjaguar** [comment]
You uncovered a sizable omission in the docs, which will be remedied in the release version. As for now, here it is:
- the palette indices of currently selected colors A and B are displayed on the settings toolbar;
- the palette index of the pixel under cursor can be displayed on the statusbar ("Preferences->Status Bar->Pixel [I] (RGB)" to enable).
(Naturally, it only works this way with an indexed image - with an RGB one, RGB values are displayed instead.)
Isn't this enough for your use case?

**Comment by madgarden** [comment]
Ah, I didn't know about the Settings toolbar... I actually never use it,
heh. ;)

But to be honest, that is a pretty clunky solution when one is used to
quickly shifting between paletted colours. A simple reverse highlight of
the selected palette index number, or an A/B icon on the right side of the
palette entry would be really nice. Quick visual check, no need to scan
around and look up numbers in odd screen locations.

**Comment by wjaguar** [comment]
Highlighting added in 3.49.12
