### ISSUE TITLE
Store config file in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by vanillajonathan** [wjaguar/mtPaint#22]
Adhere to the XDG Base Directory Specification.
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

Store the config file in `$XDG_CONFIG_HOME`. Example `/home/wjaguar/.config/mtpaint`.

**Comment by wjaguar** [comment]
While I see absolutely no reason to be stuffing _one single config file_ into a subdir, anyone is welcome to put "userINI = ~/.config/mtpaint" into /etc/mtpaint/mtpaintrc and enjoy the "improvement".
I made this configurable for a reason. Do read the docs and use the options.

**Comment by vanillajonathan** [comment]
It keeps the user's home directory clean and tidy, without being cluttered with config files from random software.

It makes it easier for the user to backup and restore config files, by having all config files in one directory.
