### ISSUE TITLE
Program does not register types for open action on File Managers?

### ISSUE THREAD

**Issue by megatux** [wjaguar/mtPaint#24]
Using ElementaryOS Loki. "Open with" action in the _Files_ manager does not give the option to use this program, even listing "All programs".

**Comment by wjaguar** [comment]
Maybe so. It is for *you* to investigate the actual cause, for this is maybe the third time ever I've even heard of an "ElementaryOS".

**Comment by megatux** [comment]
[Elementary](https://distrowatch.com/table.php?distribution=elementary)'s panthen-files use the .desktop FreeDesktop standard format.
Anyway I think I found the problem. The .desktop file in the Debian (Ubuntu?) package is wrong. The `Exec` line does not contains the parameter to the file ( "%F" ). Checked at the [Launchpad page](https://launchpad.net/mtpaint/main/3.40). After editing the .desktop file (and running the update-desktop-database program) it started to list the program on the "open with" context menu.
Probably we should report the bug to the packager.

**Comment by matyler** [comment]
Well spotted Cristian, this looks to be a distro bug.  It is present in my Lubuntu test system also, which uses "mtpaint %U" in the desktop file which stops PCManFM working via the "Open With" menu (although curiously it works fine when using Thunar/XFCE).  I've never interacted with Debian/Ubuntu so I'm not really sure how to sort this out and help their users.

**Comment by megatux** [comment]
Unsure how to follow. I don't understand the bugs section on Launchpad project :) :

![captura realizada el 2017-09-06 11 08 47](https://user-images.githubusercontent.com/850020/30116453-f8311bc8-92f3-11e7-8453-cbacee586ab1.png)

**Comment by matyler** [comment]
I think Debian may be the best place to fix the bug.  Try these links:

https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=mtpaint
https://www.debian.org/Bugs/Reporting

This way Ubuntu may catch the fix once Debian correct it.  It looks like an email to their generic address may suffice, lets hope so!  If this doesn't work, let me know and I will try to help.
