### ISSUE TITLE
enable easier translations

### ISSUE THREAD

**Issue by c-to-qtt** [wjaguar/mtPaint#25]
an easy way to get more/complete/better translations of the GUI is usage of web-based translation services such as Transifex or Launchpad. Actually, I could start such a project on Transifex if there is a chance to get the translations included in one of the next releases. However, for a better coordination of the translation process, it would be better if the project administrator (= project owner) is the code developer. I could serve as project manager for the translations in this case.

**Comment by wjaguar** [comment]
mtPaint actually has a Launchpad translation page:
https://translations.launchpad.net/mtpaint/main/+pots/mtpaint
What the project is lacking, is someone with time and inclination for the thankless tedious task of _reviewing_ the newly-translated strings; checking their actual validity and suitability, comparing them to accepted standard terminology (as in GIMP), fixing errors where possible.
There is but one of me having to do everything in this project, and I presently have enough on my plate IRL. Fixing bugs, I still do; new features, had to put on hold; cleaning up translations, am unable to bear the thought of.

This is the extent of the problem. If you can offer any help with regard to _this_, it would be appreciated greatly.

**Comment by c-to-qtt** [comment]
thanks ! good to see the launchpad site is still alive.  As I'm not very familiar with the technical terminology the task of reviewing translations is a bit over my head. However, I'll start with the German translation and will see what I can do.
thanks for keeping the program alive - I know how frustrating such a one-man-show can be...
