### ISSUE TITLE
Turning on/off the Channel Menu checkboxes via toolbar button

### ISSUE THREAD

**Issue by escapecode** [wjaguar/mtPaint#30]
![mtpaint_rclick_channels_buttons](https://user-images.githubusercontent.com/919307/45774561-4904f280-bc1b-11e8-88fc-5d3625b0f839.png)

Hi all.  I'm working on creating buttons that can disable alpha channel and hide the image channel.  Most of the code is working, and a branch of the functionality is at https://github.com/escapecode/mtPaint/tree/channel_buttons.  The issue is that I haven't figured out a way to code or script that when toggling a annels alpha/hidden value, the associated Channel menu checkbox is updated.

For a visual reference, the attached image shows the updated UI with four new buttons at the end of the toolbar (one for each channel)

**Comment by wjaguar** [comment]
For code, it is like this: **cmd_set(menu_slots[MENU_DCHAN0], hide_image);**
For script, it is like this: **-c/hide** or **-c/'disable alpha'**
But for a reason to waste toolbar space instead of setting up hotkeys, I come up empty. ;)

**Comment by escapecode** [comment]
I tried both of those options (as well as others) before I posted and they do not address the issue of toggling on/off state of the menu checkbox.  No worries, I'll work locally and find a solution.
