### ISSUE TITLE
make default tool icon configurable

### ISSUE THREAD

**Issue by redguardtoo** [wjaguar/mtPaint#33]
I use `mtpaint` as lightweight screenshot editor. So I restart it frequently. After restarting, I always click `Paint` icon at first. Is it possible to make `DEFAULT_TOOL_ICON` configurable?

I could send you pull request, do you use github to accept pull request?

**Comment by wjaguar** [comment]
Making an interface for configuring it, is orders of magnitude more complicated than pressing the F4 key even a few times a day, and would waste far more of my time than all your F4 keypresses in a lifetime, combined.
Configuration choices should NOT be worthless tweaks; any new one costs not only time which is NOT worthless to me, but code size and screen space as well.
