### ISSUE TITLE
How to paste image into browser

### ISSUE THREAD

**Issue by redguardtoo** [wjaguar/mtPaint#35]
See https://stackoverflow.com/questions/6333814/how-does-the-paste-image-from-clipboard-functionality-work-in-gmail-and-google-c

It's supported by all modern browsers now. But when I tested with latest firefox, mtpaint failed.

Other programs like pinta worked.

**Comment by wjaguar** [comment]
Edit->Export clipboard to system
As documented in section 4.6 of the handbook.
Users who on principle do not read documentation, have only themselves to blame.
