### ISSUE TITLE
Why no releases?

### ISSUE THREAD

**Issue by nunotexbsd** [wjaguar/mtPaint#51]
Hello,

Why there is no releases available?
Is there a future plan to have releases?

I'm maintaining FreeBSD port and I need to use tags.

Thanks,

Nuno Teixeira

**Comment by wjaguar** [comment]
As to the why, it is as I said here:
https://github.com/wjaguar/mtPaint/issues/8#issuecomment-775460880

A request for tags was already made there, but till now I have received no explanation what actual practical function said tags would serve in THIS specific case.
The function "sit there and clutter the interface for me" is rather opposite of practical, so they need some redeeming quality.

As to actual releases, it is as I said here:
https://github.com/wjaguar/mtPaint/issues/8#issuecomment-775583292
The 3.51 update release will be when I run out of stuff to fix in the 3.50.xx branch (I hope that time is not distant).

**Comment by nunotexbsd** [comment]
Hello!

Thank you for the explanation.

I will wait for 3.51 update release :)

Cheers,

Nuno Teixeira
