### ISSUE TITLE
Drawing lines works fine, but arrowheads don't appear

### ISSUE THREAD

**Issue by cheapy** [wjaguar/mtPaint#53]
Maybe its just how I'm doing it.  I am trying to annotate a picture, drawing a line pointing to something on the picture, and then typing some text next to the end of the line to explain why pointed to it.  

I select the line draw tool.  When do I type the a or s to tell it to draw the arrowhead at the end of the line?  The line works and I can adjust its thickness or color.

Can you think of any reason the arrowhead wouldn't work?

Thanks

**Comment by wjaguar** [comment]
http://mtpaint.sourceforge.net/handbook/en_GB/chap_03.html#SEC241
**3.2.4.1 Drawing Arrows**
*The straight line tool can also draw an arrow head at the end of the current line if you press either the 'A' or 'S' keys for an open or closed head. The size of the head is determined by the tool flow. If you set the flow value too low, the arrowhead will be drawn too small to be visible at all.*

I wonder. Is the handbook cursed with a permanent Notice-Me-Not, or what?

**Comment by cheapy** [comment]
Please be nice.  When I found out that MTPaint had the arrow capability (and the hot keys), I spent some time trying, with both a and s, both lower case and upper, both before drawing the line and after, on antiX 19.3, and then dowloaded the source, and compiled it, and tried again.
![screenshot_5](https://user-images.githubusercontent.com/7473967/109545451-80d01f80-7a8e-11eb-967c-45a4b6fcc122.jpg)

**Comment by cheapy** [comment]
BTW, I did find your manual, and it looks great and obviously a lot of effort has gone into it.  I'm sorry I hadn't found it before.  I had found the arrowhead keys in your help doc here https://github.com/wjaguar/mtPaint/blob/master/doc/HELP.   I hadn't installed the documentation package, and the default setup on antiX did not bring up the web version.  I tried to configure it to use /usr/bin/x-www-browser with the URL http://mtpaint.sourceforge.net/handbook/ from your sourceforge site, but still get the can't find the documentation error.  I finally installed the documentation package, and now the manual comes up. 

As for the arrowheads, I am guessing I have something configured wrong, but don't know what.

**Comment by wjaguar** [comment]
As to documentation, you need a local file for that. Say, this one:
```
<meta http-equiv="Refresh" content="0; url='http://mtpaint.sourceforge.net/handbook/'" />
```

**Comment by cheapy** [comment]
That fixed it.  I didn't have the settings toolbar on the screen so I thought that "flow" meant the width of the line like in the programs like flameshot.  The default flow is 1.  The arrowhead still doesn't appear at 10, but at 16 it does.  Sorry for misunderstanding it.

I will try the URL after work...

**Comment by cheapy** [comment]
I did try the value you gave to get the help from the web, but still got the error message box.  

Since the distro does not by default include the documentation package (minimizing space required), it would be nice to be able to open it via the browser, but for me, now having installed the package, its not worth fighting.

If you think of another way to try it, post here and I will, and if we get it working, I'll talk to the Devs and get whatever is needed setup.  Thanks again for a great program and helping me figure out my error.

**Comment by wjaguar** [comment]
It is not "the value", it is the content to be saved into a HTML file *the name of which should then be the value*.
Some Puppy Linux variants, to save space, used either a similar redirect file, or a copy of handbook's title page with absolute links, such as the one here: http://murga-linux.com/puppy/viewtopic.php?p=805693#805693

**Comment by cheapy** [comment]
I will offer that solution, thanks

**Comment by cheapy** [comment]
Based on the above I've experimented with using MTPaint that has led me to a few easier followup questions  
1. I want to default flow to 12.  Can I add a line to ~/.mtpaint to do that?  What would the syntax be?
2. I want to default to a round or square brush (2nd or 3rd one down), and make it 2 or 3 wide instead of 1.  Can I add a line to ~/.mtpaint to do that?  What would the syntax be?
3. Is there a document that tells how to use the Script function?
4. We are discussing adding a custom Action to upload the current pic to Imgur or similar.  Do you already something setup to do something like that?

Thanks for the help :)

**Comment by wjaguar** [comment]
The poor handbook definitely is under a curse. :)
http://mtpaint.sourceforge.net/handbook/en_GB/chap_10.html

As to changing default flow or default brush, at present the only possible solution is a script like this:
```
-e/set flow=12 -e/brush type=circle size=3
```
http://mtpaint.sourceforge.net/handbook/en_GB/chap_10.html#SEC52
Even with that, presently there is no option to run script at startup (because no one asked for it); but adding it to menu/binding it to hotkey might be enough for doing such initial setup.

As to uploading to Imgur, seems they may have a tool for it linked here:
https://help.imgur.com/hc/en-us/articles/209592766-Tools-for-Imgur
"Bart's Bash Script Uploader"
If the thing works, then "imgur.sh %f" will be the action.

**Comment by cheapy** [comment]
Thanks very much.  There is no chapter 10 in the installed manual (3.50 from 2016 is current from Debian).  Hopefully they will update it with Bullseye.  That's another good reason to have it available from the web.
