### ISSUE TITLE
Add 80% zoom level

### ISSUE THREAD

**Issue by cheapy** [wjaguar/mtPaint#54]
When working with full screen screenshots, 100% is too large because the whole picture will never fit, and at 50% its difficult to see much detail, but much of the screen isn't used.  It would need to be selectable by script for this to be useful in the screenshot application I'm working on.

**Comment by cheapy** [comment]
I think I figured out a way with a script

**Comment by wjaguar** [comment]
Zoom levels in mtPaint are limited to N and 1/N: integer multiplies and integer fractions. This fact is relied upon throughout the renderer and inside the mouse handler.
To allow in-between zoom factors such as 80% or 150% or whatever, would require a rewrite of large parts of mainwindow.c
Too much hassle for too little gain, as I see it.

**Comment by cheapy** [comment]
I got around it by reducing the original to 80% via --cmd script before running MTPaint interactively, so not a problem.  I admit, I wish I had the ability to run a script automatically at startup interactively, but I got around that using xdotool with a keyboard shortcut

**Comment by wjaguar** [comment]
Startup script can be added trivially, if need be: by making a reserved action name, or a reserved substring in it, to mean "Run at startup".
Say, everything with "INIT" bracketed by paired punctuation in the name, like this:
```
Initscript (INIT)
Another /INIT/ initscript
#INIT# Hidden initscript
```
Or would you prefer some other identifying string for it?

**Comment by cheapy** [comment]
I am running MTPaint for a special purpose from a script, so only want it to change the setups to my special setup when its run from my bash script.  I either need to pass it the name of a special config file or a startup to run if I want it to.  This is the dialog before i take the pic and then call MTPaint:
![screenshot-dialog](https://user-images.githubusercontent.com/7473967/110424023-b9ac5d80-8067-11eb-8144-821e13a79998.jpg)

**Comment by wjaguar** [comment]
Maybe an environment variable then? MTPAINT_INIT=...
Or even two, with MTPAINT_INI=... for substituting a nondefault inifile.

**Comment by cheapy** [comment]
Yes, that would be great.    The init is similar to what I'm doing but cleaner.  The ini is also a good idea.

**Comment by wjaguar** [comment]
Variables added in 3.50.07

**Comment by cheapy** [comment]
I've got it compiled and working and will change the code to use your new options this weekend.
