### ISSUE TITLE
SIZE_MAX is not defined

### ISSUE THREAD

**Issue by 12Me21** [wjaguar/mtPaint#56]
https://github.com/wjaguar/mtPaint/blob/4ea607e44f7fe9373d399f56d59e048d62034619/src/png.c#L94-L96
For me, this error is always thrown during compilation (the comparison is always falsey because SIZE_MAX isn't defined here)
Including <stdint.h> would fix this.

**Comment by wjaguar** [comment]
Thanks. The header is dragged in by both libopenjpeg and libwebp headers so I hadn't noticed the problem.

**Comment by wjaguar** [comment]
Fixed in 3.50.09
