### ISSUE TITLE
Opacity not available for painting or other tools

### ISSUE THREAD

**Issue by jonpatterns** [wjaguar/mtPaint#72]
Hi

I'm using mtPaint 3.50.09 on Manjaro Linux

Opacity setting is permanently grayed out in the settings toolbar

Selecting paint or any selection option, or changing other settings in toolbar doesn't not seem to help.

Thanks : -)

**Comment by wjaguar** [comment]
Barring Cthulhu's direct intervention, this most likely means you are working on an indexed image.
The section 3.5 of the handbook says: "With indexed images, the opacity control is disabled (greyed out)."
https://mtpaint.sourceforge.net/handbook/en_GB/chap_03.html#SEC5
If you want to use opacity mode with it, convert it to RGB: Image->Convert to RGB
If you create a new image, choose "24 bit RGB" in the "New image" dialog; the choice will be remembered after that.

**Comment by jonpatterns** [comment]
Thanks for the reply. That was indeed the problem. I did look at the manual but obviously not closely enough.
