### ISSUE TITLE
Paste text is disabled in --cmd mode

### ISSUE THREAD

**Issue by cheapy** [wjaguar/mtPaint#73]
I have an icon with clouds on it.  Without any user or screen interaction, in a script I am trying to:

1. Put the current temperature string 57F into a special mtpaint.conf as the textString 
2. Run mtpaint in --cmd mode to open the file, setup the brush, paste the text string (ex: 57F) onto it, and save the file.

When i try to do that it says:

mtp_conf: /home/bobc/.config/mti-icon/mtpaint.conf
+ echo 'textString = 57F'
+ echo 'Running mtpaint'
Running mtpaint
+ mtpaint --cmd -f/o=/home/bobc/.config/mti-icon/current_icon.png -e/set flow=12 -e/brush type=circle size=2 '-e/Paste text' -file/as=/home/bobc/.cache/mti-icon/weather-fog57F.png form=png -f/q
'-e/Paste text' matches a disabled item

When I try to do it using MTPAINT_INIT instead of the command line, it flashes on the screen and gets a GTK error
+ echo 'textString = 57F'
+ export 'MTPAINT_INIT=-e/set flow=12 -e/brush type=circle size=2 -e/'\''Paste text'\'' -file/as=/home/bobc/.cache/mti-icon/weather-fog57F.png form=png -f/q'
+ MTPAINT_INIT='-e/set flow=12 -e/brush type=circle size=2 -e/'\''Paste text'\'' -file/as=/home/bobc/.cache/mti-icon/weather-fog57F.png form=png -f/q'
+ echo 'Running mtpaint'
Running mtpaint
+ mtpaint /home/bobc/.config/mti-icon/current_icon.png

(mtpaint:32117): Gtk-CRITICAL **: 02:37:55.385: IA__gtk_window_set_title: assertion 'GTK_IS_WINDOW (window)' failed

Could you please suggest what I'm doing wrong, or perhaps a way to accomplish it?

Thanks

**Comment by wjaguar** [comment]
The regular "Paste Text" is incurably dependent on GTK+ GUI stuff, thus its failing in the init phase for no window yet. It is disabled in commandline mode to prevent exactly that thing, and the fact is documented (section 10.5.2 of the handbook).

If you specifically want the GTK+ text engine, you launch your script from within a running GUI instance of mtPaint. Either paste it into the script-configure window, or launch it from there by reference like this: -i/script=file.cmd
If you instead want commandline mode and need some text there, you use the FreeType text engine: -e/freetype

**Comment by wjaguar** [comment]
A thing worth note: on my system, there is NO error when I run:
MTPAINT_INIT="-e/set flow=12 -e/brush type=circle size=2 -e/text text=test -e/centre -f/as=ather-fog57F.png form=png -f/q" ./mtpaint
Neither with a GTK+2 build, nor with a GTK+3 one.

And, as you can see from the above example, your MTPAINT_INIT script cannot do what it should be doing, for two reasons:
- one, you forgot to pass the actual text string to the text engine (the "text=..." part)
- two, you forgot to actually paste the rendered text (the "-e/centre" command; you'll need a "-e/centre (x,y)"  if you want to place your text around a specific point, see handbook section 10.5.2)

Also, the scripts run from MTPAINT_INIT do ask user's confirmation for overwriting files, and (if "Confirm exit" is enabled) for quitting too. I'll fix that oversight now that I see the use case, but in the meantime, be prepared: delete the old file if any, and disable the pref, before using the script.

**Comment by cheapy** [comment]
Sorry, the string itself was in my mtpaint.conf textString value.  It worked fine in GUI mode, but in this case I needed it to work in cmd mode.

Yes, I found out about the confirm overwrite, and just avoided it by never having the file to be written already there.

Thanks for all the effort you put into the program, documentation, and answering questions.
