### ISSUE TITLE
Feature request: headless, GTKless build

### ISSUE THREAD

**Issue by danboid** [wjaguar/mtPaint#76]
It would be cool if it was possible to build mtpaint without any GTK/GUI support so that people could use it for scripting some graphics tasks on machines without a display and/or a with a very small amount of RAM.

Do you think a headless version could run with only 4 MB RAM?

**Comment by wjaguar** [comment]
mtPaint uses the GLib part of GTK+ unconditionally, for string operations and threading. While excluding the other parts, as in not linking to them, is technically possible, is suspect it will not save the day for you anyway, given that the mtPaint binary itself these days is about 800k in size, and its uninitialized data size is another 1360k. On top of that, the smallest GLib (of GTK+1) is another 170k, libpng (required) is yet another 150k, libz (required by it) is 90k, libjpeg is another 240k at the very least, libfreetype (needed if you want text in headless mode) weighs 640k, the smallest liblcms (color management) is 220k, and libc (required by everything) is not exactly tiny either, even its embedded variants. And everything listed has a bit of its own uninitialized data as well.

mtPaint never targeted memory-starved setups (even the machine I had back then in 2006, already had 64 MB), therefore it requires free RAM of at least twice the uncompressed image size to work properly. That limits the dimensions of what you could process in 1 MB (after the binary and the libs and the stack eat the other 3) to something near useless.

Which returns us to the "without any GTK+" question; not linking to the GUI part (1.5 MB even with GTK+1) would make sense when trying to make do with 8 MB, but for mere 4 MB it cannot save the day anyway.

**Comment by danboid** [comment]
Oh OK. Thanks for the breakdown anyway.
